config/routes.rb
Rails.application.routes.draw do
  resources :svg_images
  resources :cargo
  resources :ships
  resources :people
  get 'welcome/index'
  authenticate :user do
    get '/dashboard', to: 'welcome#dashboard'
    post '/dashboard/new_color',
         to: 'welcome#new_color',
         as: :new_color
    #get '/launch/existing-or-new',
    #    to: 'welcome#existing_or_new',
    #    as: :begin_launch_wizard
    get '/launch/new-ship',
        to: 'welcome#new_ship_info',
        as: :launch_wizard_new_ship_info
    get '/launch/new-ship/picture',
        to: 'welcome#new_ship_picture',
        as: :launch_wizard_new_ship_picture
    post '/launch/new-ship/picture',
         to: 'welcome#set_new_ship_picture',
         as: :launch_wizard_set_new_ship_picture
    get '/launch/new-ship/summary',
        to: 'welcome#new_ship_summary',
        as: :launch_wizard_new_ship_done

    get '/launch/radar',
        to: 'welcome#radar',
        as: :radar
  end

  root 'welcome#index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cargo.rb
# == Schema Information
#
# Table name: cargo
#
#  id            :integer          not null, primary key
#  safefy_rating :integer
#  description   :text(65535)
#  person_id     :integer
#  weight        :decimal(10, )
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Cargo < ApplicationRecord
  belongs_to :person
end

app/controllers/cargo_controller.rb
class CargoController < ApplicationController
  before_action :set_cargo, only: [:show, :edit, :update, :destroy]

  before_filter :restrict_access_to_admins, except: [:index, :show]
  # GET /cargo
  # GET /cargo.json
  def index
    @cargo = Cargo.all
  end

  # GET /cargo/1
  # GET /cargo/1.json
  def show
  end

  # GET /cargo/new
  def new
    @cargo = Cargo.new
  end

  # GET /cargo/1/edit
  def edit
  end

  # POST /cargo
  # POST /cargo.json
  def create
    @cargo = Cargo.new(cargo_params)

    respond_to do |format|
      if @cargo.save
        format.html { redirect_to @cargo, notice: 'Cargo was successfully created.' }
        format.json { render :show, status: :created, location: @cargo }
      else
        format.html { render :new }
        format.json { render json: @cargo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cargo/1
  # PATCH/PUT /cargo/1.json
  def update
    respond_to do |format|
      if @cargo.update(cargo_params)
        format.html { redirect_to @cargo, notice: 'Cargo was successfully updated.' }
        format.json { render :show, status: :ok, location: @cargo }
      else
        format.html { render :edit }
        format.json { render json: @cargo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cargo/1
  # DELETE /cargo/1.json
  def destroy
    @cargo.destroy
    respond_to do |format|
      format.html { redirect_to cargo_index_url, notice: 'Cargo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cargo
      @cargo = Cargo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cargo_params
      params.require(:cargo).permit(:safefy_rating, :description, :person_id, :weight)
    end
end

app/helpers/cargo_helper.rb
module CargoHelper
end

app/views/cargo/_form.html.erb
<%= form_for(cargo) do |f| %>
  <% if cargo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cargo.errors.count, "error") %> prohibited this cargo from being saved:</h2>

      <ul>
      <% cargo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :safefy_rating %>
    <%= f.number_field :safefy_rating %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :person_id %>
    <%= f.text_field :person_id %>
  </div>

  <div class="field">
    <%= f.label :weight %>
    <%= f.text_field :weight %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cargo/edit.html.erb
<h1>Editing Cargo</h1>

<%= render 'form', cargo: @cargo %>

<%= link_to 'Show', @cargo %> |
<%= link_to 'Back', cargo_index_path %>

app/views/cargo/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cargo</h1>

<table>
  <thead>
    <tr>
      <th>Safefy rating</th>
      <th>Description</th>
      <th>Person</th>
      <th>Weight</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cargo.each do |cargo| %>
      <tr>
        <td><%= cargo.safefy_rating %></td>
        <td><%= cargo.description %></td>
        <td><%= cargo.person %></td>
        <td><%= cargo.weight %></td>
        <td><%= link_to 'Show', cargo %></td>
        <td><%= link_to 'Edit', edit_cargo_path(cargo) %></td>
        <td><%= link_to 'Destroy', cargo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cargo', new_cargo_path %>

app/views/cargo/new.html.erb
<h1>New Cargo</h1>

<%= render 'form', cargo: @cargo %>

<%= link_to 'Back', cargo_index_path %>

app/views/cargo/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Safefy rating:</strong>
  <%= @cargo.safefy_rating %>
</p>

<p>
  <strong>Description:</strong>
  <%= @cargo.description %>
</p>

<p>
  <strong>Person:</strong>
  <%= @cargo.person %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @cargo.weight %>
</p>

<%= link_to 'Edit', edit_cargo_path(@cargo) %> |
<%= link_to 'Back', cargo_index_path %>