config/routes.rb
Rails.application.routes.draw do
  resources :svg_images
  resources :cargo
  resources :ships
  resources :people
  get 'welcome/index'
  authenticate :user do
    get '/dashboard', to: 'welcome#dashboard'
    post '/dashboard/new_color',
         to: 'welcome#new_color',
         as: :new_color
    #get '/launch/existing-or-new',
    #    to: 'welcome#existing_or_new',
    #    as: :begin_launch_wizard
    get '/launch/new-ship',
        to: 'welcome#new_ship_info',
        as: :launch_wizard_new_ship_info
    get '/launch/new-ship/picture',
        to: 'welcome#new_ship_picture',
        as: :launch_wizard_new_ship_picture
    post '/launch/new-ship/picture',
         to: 'welcome#set_new_ship_picture',
         as: :launch_wizard_set_new_ship_picture
    get '/launch/new-ship/summary',
        to: 'welcome#new_ship_summary',
        as: :launch_wizard_new_ship_done

    get '/launch/radar',
        to: 'welcome#radar',
        as: :radar
  end

  root 'welcome#index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

  def dashboard
    @user = current_user
    @ship = current_user.ship
  end

  def existing_or_new
    @wizard_step = 0
  end

  def new_ship_info
    @wizard_step = 1
    @ship = Ship.new
  end

  def new_ship_picture
    @wizard_step = 2
    @picture_options = SvgImage.all
  end

  def set_new_ship_picture
    ship = current_user.ship
    svg = SvgImage.find(params[:picture])
    ship.svg_image = svg
    return redirect_to launch_wizard_new_ship_done_path if ship.save

    redirect_to launch_wizard_set_new_ship_picture_path, alert: 'failed to save picture'
  end

  def new_ship_summary
    @wizard_step = 3
    @ship = current_user.ship
  end

  def radar
    @ship = current_user.ship
    @skip_footer = true
  end

  def new_color
    current_user.get_new_color
    redirect_to dashboard_path if current_user.save
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/dashboard.html.erb
<div class="page-header">
  <h1>User Dashboard</h1>
</div>
<div class="row">
  <div class="col-sm-12 col-lg-4">
    <div class="panel panel-default">
      <div class="panel-heading">You</div>
      <div class="panel-body">
        <dl class="dl-horizontal">
          <dt>Color</dt>
          <dd style="color: <%= @user.color %>">
            <i class="glyphicon glyphicon-user"></i>
            <%= @user.color %>
            <%= button_to 'get new color', new_color_path, class: 'btn btn-primary btn-xs' %>
          </dd>
          <dt>User ID</dt>
          <dd><%= @user.id %></dd>
          <dt>Email</dt>
          <dd><%= @user.email %></dd>
          <dt>Sign In Count</dt>
          <dd><%= @user.sign_in_count %></dd>
          <dt>IP</dt>
          <dd><%= @user.current_sign_in_ip %></dd>
          <dt>Account Age</dt>
          <dd><%= time_ago_in_words(@user.created_at) %></dd>
        </dl>
      </div>
    </div>
  </div>
  <div class="col-sm-6 col-lg-4">
    <% if @ship.nil? %>
        <div class="panel panel-default">
          <div class="panel-heading">Your Current Ship</div>
          <div class="panel-body">
            <div class="alert alert-warning" role="alert">You haven't created a ship yet! You should do that:
              <%= link_to "Create a Ship", launch_wizard_new_ship_info_path, class: "alert-link" %>
            </div>
          </div>
        </div>
    <% else %>
        <%= render partial: 'partials/ship_panel' %>
    <% end %>
  </div>
  <div class="col-sm-6 col-lg-4">
    <div class="panel panel-default">
      <div class="panel-heading">Available Actions</div>
      <div class="panel-body">
        <div class="media">
          <div class="media-left">
            <% if @ship.nil? %>
                <%= image_tag "radar.svg", width: 64 %>
            <% else %>
                <%= link_to radar_path do %>
                    <%= image_tag "radar.svg", width: 64 %>
                <% end %>
            <% end %>
          </div>
          <div class="media-body">
            <h4 class="media-heading">
              <% if @ship.nil? %>
                <del>Launch Ship</del>
                (<%= link_to "create a ship", launch_wizard_new_ship_info_path, class: "alert-link" %> first)
              <% else %>
                  <%= link_to "Launch Ship", radar_path %>
              <% end %>
            </h4>
            See a live view of other ships flying around in space.
          </div>
        </div>
        <div class="media">
          <div class="media-left">
            <%= link_to launch_wizard_new_ship_info_path, class: "alert-link" do %>
                <%= image_tag "xwing.svg", width: 64 %>
            <% end %>
          </div>
          <div class="media-body">
            <h4 class="media-heading">
              <%= link_to "Create a New Ship", launch_wizard_new_ship_info_path, class: "alert-link" %>
            </h4>
            Choose a ship that you can pilot around in the live pilot ship view.
          </div>
        </div>
        <div class="media">
          <div class="media-left">
            <%= link_to(destroy_user_session_path, :method => :delete) do %>
                <%= image_tag "exit.svg", width: 64 %>
            <% end %>
          </div>
          <div class="media-body">
            <h4 class="media-heading">
              <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
            </h4>
            End your session.
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/welcome/existing_or_new.html.erb
<%= render partial: 'partials/launch_wizard_header' %>
<div class="text-center">
  <div><%= link_to "Create New Ship", launch_wizard_new_ship_info_path, class: "btn btn-primary btn-lg" %></div>
</div>

app/views/welcome/index.html.erb
<% unless user_signed_in? %>
    <div class="alert alert-info">
      To pilot a ship you have to be logged in.
      <%= link_to 'log in', new_user_session_path, :class => "alert-link" %>
      or
      <%= link_to 'sign up', new_user_registration_path, :class => "alert-link" %>
    </div>
<% end %>
<div class="jumbotron jumbotron-welcome">
  <h1>Starport Operations Center</h1>
    <p>Build your very own starship and pilot it around the galaxy. Spread wow factor across the universe.</p>
  <% if user_signed_in? %>
      <p>
        <%= link_to "Go To User Dashboard", dashboard_path, :class => "btn btn-primary btn-lg" %>
      </p>
  <% else %>
      <p>
        <%= link_to "Get Started", new_user_session_path, :class => "btn btn-primary btn-lg" %>
      </p>
  <% end %>
</div>
<div class="page-header">
  <h1>Starport Management</h1>
</div>
<div class="row">
  <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
      <%= image_tag "ripley.jpg", class: "max-height-image" %>
      <div class="caption">
        <h3>User Dashboard</h3>
        <p>Visit your user dashboard. Build your ship and pilot it.</p>
        <p><%= link_to "User Dashboard", dashboard_path, :class => "btn btn-primary" %></p>
      </div>
    </div>
  </div>
  <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
      <%= image_tag "troopers.jpg", class: "max-height-image" %>
      <div class="caption">
        <h3>People</h3>
        <p>View a list of people</p>
        <p><%= link_to "Manage People", people_path, :class => "btn btn-primary" %></p>
      </div>
    </div>
  </div>
  <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
      <%= image_tag "ship.jpg", class: "max-height-image" %>
      <div class="caption">
        <h3>Ships</h3>
        <p>View a list of ships</p>
        <p><%= link_to "Manage Ships", ships_path, :class => "btn btn-primary" %></p>
      </div>
    </div>
  </div>
  <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
      <%= image_tag "xwing.svg", class: "max-height-image" %>
      <div class="caption">
        <h3>Manage SVG Images</h3>
        <p>SVG Images are used to build and customize ships</p>
        <p><%= link_to "Manage SVG Images", svg_images_path, :class => "btn btn-primary" %></p>
      </div>
    </div>
  </div>
</div>
<div class="page-header">
  <h1>Starport Schema</h1>
</div>
<div class="row">
  <div class="jumbotron text-center">
    <a href="/erd.svg">
      <img src="/erd.svg" style="max-width: 500px; margin: 0 auto;">
    </a>
    <p>
      <a href="/erd.svg" class="btn btn-default">View Detailed ERD</a>
      <a href="/erd.pdf" class="btn btn-default">View Rails ERD</a>
    </p>
  </div>
</div>

app/views/welcome/new_ship_info.html.erb
<%= render partial: 'partials/launch_wizard_header' %>
<h2>Ship Info</h2>
<%= form_for(@ship) do |f| %>
    <% if @ship.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@ship.errors.count, "error") %> prohibited this ship from being saved:</h2>

          <ul>
            <% @ship.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="form-group">
      <%= f.label :name, "Ship Name (required)" %>
      <%= f.text_field :name, class: "form-control", required: true, placeholder: "enter your ship's name" %>
      <div class="help-block">
        Name for your ship. We use the same naming conventions as terrestrial naval vessels in space FYI.
      </div>
    </div>

    <div class="form-group">
      <%= f.label :ship_class %>
      <%= f.text_field :ship_class, class: "form-control", placeholder: "enter a ship class" %>
      <div class="help-block">
        See <a href="https://en.wikipedia.org/wiki/List_of_naval_ship_classes_in_service">ship classes</a>. Not really used for anything.
      </div>
    </div>

    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: "form-control", placeholder: "describe your ship" %>
      <div class="help-block">
        Will be displayed on your ship's profile.
      </div>
    </div>

    <div class="form-group">
      <%= f.label :passenger_capacity %>
      <%= f.number_field :passenger_capacity, class: "form-control", min: 0, placeholder: "enter passenger capacity" %>
      <div class="help-block">
        Does your ship hold passengers? How many?
      </div>
    </div>

    <div class="form-group">
      <%= f.label :base_fare, "Base fare (in dollars)" %>
      <%= f.text_field :base_fare, class: "form-control", placeholder: "enter base fare" %>
      <div class="help-block">
        How much does it cost to hire your ship for a trip?
      </div>
    </div>

    <div class="form-group">
      <%= f.label :shield_rating %>
      <%= f.number_field :shield_rating, class: "form-control", min: 0, placeholder: "enter shield rating" %>
      <div class="help-block">
        If your ship has shields: give it a shield rating. A respectable shield would have a rating of around 100.
      </div>
    </div>

    <div class="form-group">
      <%= f.label :armor_rating %>
      <%= f.number_field :armor_rating, class: "form-control", placeholder: "enter armor rating" %>
      <div class="help-block">
        If your shield has armor: give it an armor rating. Usually this is around 100 for regular military vessels. A heavily armored ship could have a rating in the thousands.
      </div>
    </div>

    <div class="form-group">
      <%= f.label :cargo_capacity, "Cargo Capacity (in kilograms)" %>
      <%= f.text_field :cargo_capacity, class: "form-control", placeholder: "enter cargo capacity" %>
      <div class="help-block">
        How many kilograms of cargo can your ship hold?
      </div>
    </div>

    <div class="actions">
      <input type="hidden" name="is_launch_wizard" value="true" />
      <%= f.submit "Next", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/welcome/new_ship_picture.html.erb
<%= render partial: 'partials/launch_wizard_header' %>
<%= form_tag launch_wizard_set_new_ship_picture_path, method: "post" do %>
  <table class="table">
    <% @picture_options.each do |picture| %>
      <tr>
        <td style="vertical-align: middle" width="20">
          <input id="p-<%= picture.id %>" type="radio" name="picture" value="<%= picture.id %>" title="<%= picture.id %>">
        </td>
        <td>
          <label for="p-<%= picture.id %>">
            <div style="max-width: 150px">
              <img src="<%= raw picture.colorized_image_url(current_user.color) %>">
            </div>
          </label>
        </td>
      </tr>
    <% end %>
  </table>
  <input type="submit" name="commit" value="Next" class="btn btn-primary" />
<% end %>

app/views/welcome/new_ship_summary.html.erb
<%= render partial: 'partials/launch_wizard_header' %>
<div class="row">
  <div class="col-sm-12">
    <%= render partial: 'partials/ship_panel' %>
  </div>
</div>

app/views/welcome/radar.html.erb
<script>
  window.CURRENT_USER = "<%= current_user.email %>";
  window.CURRENT_USER_COLOR = "<%= current_user.color %>";
</script>
<div id="radar_entry">
  Loading<span class="blink">...</span>
</div>