config/routes.rb
Rails.application.routes.draw do
  resources :svg_images
  resources :cargo
  resources :ships
  resources :people
  get 'welcome/index'
  authenticate :user do
    get '/dashboard', to: 'welcome#dashboard'
    post '/dashboard/new_color',
         to: 'welcome#new_color',
         as: :new_color
    #get '/launch/existing-or-new',
    #    to: 'welcome#existing_or_new',
    #    as: :begin_launch_wizard
    get '/launch/new-ship',
        to: 'welcome#new_ship_info',
        as: :launch_wizard_new_ship_info
    get '/launch/new-ship/picture',
        to: 'welcome#new_ship_picture',
        as: :launch_wizard_new_ship_picture
    post '/launch/new-ship/picture',
         to: 'welcome#set_new_ship_picture',
         as: :launch_wizard_set_new_ship_picture
    get '/launch/new-ship/summary',
        to: 'welcome#new_ship_summary',
        as: :launch_wizard_new_ship_done

    get '/launch/radar',
        to: 'welcome#radar',
        as: :radar
  end

  root 'welcome#index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ship.rb
# == Schema Information
#
# Table name: ships
#
#  id                 :integer          not null, primary key
#  name               :string(255)
#  ship_class         :string(255)
#  description        :text(65535)
#  photo_url          :string(255)
#  passenger_capacity :integer
#  base_fare          :decimal(10, )
#  shield_rating      :integer
#  armor_rating       :integer
#  cargo_capacity     :decimal(10, )
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

class Ship < ApplicationRecord
  has_many :crew_slot_assignments
  has_one :user
  belongs_to :svg_image

  after_initialize :init

  def self.find_cached(id)
    Rails.cache.fetch("ship/#{id}", expires_in: 5.minute) do
      find(id)
    end
  end

  private

  def init
    self.svg_image ||= SvgImage.first
  end
end

app/controllers/ships_controller.rb
class ShipsController < ApplicationController
  before_action :set_ship, only: [:show, :edit, :update, :destroy]

  before_filter :restrict_access_to_admins, except: [:index, :create, :show]
  # GET /ships
  # GET /ships.json
  def index
    @ships = Ship.all
  end

  # GET /ships/1
  # GET /ships/1.json
  def show
  end

  # GET /ships/new
  def new
    @ship = Ship.new
  end

  # GET /ships/1/edit
  def edit
  end

  # POST /ships
  # POST /ships.json
  def create
    @ship = Ship.new(ship_params)

    respond_to do |format|
      if @ship.save
        format.html do
          if params[:is_launch_wizard]
            current_user.ship = @ship
            current_user.save
            return redirect_to launch_wizard_new_ship_picture_path(ship_id: @ship.id), notice: 'Ship was successfully created.'
          end
          redirect_to @ship, notice: 'Ship was successfully created.'
        end
        format.json { render :show, status: :created, location: @ship }
      else
        format.html { render :new }
        format.json { render json: @ship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ships/1
  # PATCH/PUT /ships/1.json
  def update
    respond_to do |format|
      if @ship.update(ship_params)
        format.html { redirect_to @ship, notice: 'Ship was successfully updated.' }
        format.json { render :show, status: :ok, location: @ship }
      else
        format.html { render :edit }
        format.json { render json: @ship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ships/1
  # DELETE /ships/1.json
  def destroy
    @ship.destroy
    respond_to do |format|
      format.html { redirect_to ships_url, notice: 'Ship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ship
      @ship = Ship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ship_params
      params.require(:ship).permit(:name, :ship_class, :description, :passenger_capacity, :base_fare, :shield_rating, :armor_rating, :cargo_capacity)
    end
end

app/helpers/ships_helper.rb
module ShipsHelper
end

app/views/ships/_form.html.erb
<%= form_for(ship) do |f| %>
  <% if ship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ship.errors.count, "error") %> prohibited this ship from being saved:</h2>

      <ul>
      <% ship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :ship_class %>
    <%= f.text_field :ship_class %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :photo_url %>
    <%= f.text_field :photo_url %>
  </div>

  <div class="field">
    <%= f.label :passenger_capacity %>
    <%= f.number_field :passenger_capacity %>
  </div>

  <div class="field">
    <%= f.label :base_fare %>
    <%= f.text_field :base_fare %>
  </div>

  <div class="field">
    <%= f.label :shield_rating %>
    <%= f.number_field :shield_rating %>
  </div>

  <div class="field">
    <%= f.label :armor_rating %>
    <%= f.number_field :armor_rating %>
  </div>

  <div class="field">
    <%= f.label :cargo_capacity %>
    <%= f.text_field :cargo_capacity %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ships/edit.html.erb
<h1>Editing Ship</h1>

<%= render 'form', ship: @ship %>

<%= link_to 'Show', @ship %> |
<%= link_to 'Back', ships_path %>

app/views/ships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ships</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Ship class</th>
      <th>Description</th>
      <th>Photo url</th>
      <th>Passenger capacity</th>
      <th>Base fare</th>
      <th>Shield rating</th>
      <th>Armor rating</th>
      <th>Cargo capacity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ships.each do |ship| %>
      <tr>
        <td><%= ship.name %></td>
        <td><%= ship.ship_class %></td>
        <td><%= ship.description %></td>
        <td><%= ship.photo_url %></td>
        <td><%= ship.passenger_capacity %></td>
        <td><%= ship.base_fare %></td>
        <td><%= ship.shield_rating %></td>
        <td><%= ship.armor_rating %></td>
        <td><%= ship.cargo_capacity %></td>
        <td><%= link_to 'Show', ship %></td>
        <td><%= link_to 'Edit', edit_ship_path(ship) %></td>
        <td><%= link_to 'Destroy', ship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ship', new_ship_path %>

app/views/ships/new.html.erb
<h1>New Ship</h1>

<%= render 'form', ship: @ship %>

<%= link_to 'Back', ships_path %>

app/views/ships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ship.name %>
</p>

<p>
  <strong>Ship class:</strong>
  <%= @ship.ship_class %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ship.description %>
</p>

<p>
  <strong>Photo url:</strong>
  <%= @ship.photo_url %>
</p>

<p>
  <strong>Passenger capacity:</strong>
  <%= @ship.passenger_capacity %>
</p>

<p>
  <strong>Base fare:</strong>
  <%= @ship.base_fare %>
</p>

<p>
  <strong>Shield rating:</strong>
  <%= @ship.shield_rating %>
</p>

<p>
  <strong>Armor rating:</strong>
  <%= @ship.armor_rating %>
</p>

<p>
  <strong>Cargo capacity:</strong>
  <%= @ship.cargo_capacity %>
</p>

<%= link_to 'Edit', edit_ship_path(@ship) %> |
<%= link_to 'Back', ships_path %>